###consul服务端口号
server:
  port: 80

spring:
  application:
    name: cloud-consunmer-order
  ####consul注册中心地址
  cloud:
    consul:
      host: 192.168.10.128
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true